name: "OpenAI Changelog Generator"
description: "Use AI to generate a non-technical, human-readable changelog for your release notes."
inputs:
  github-token:
    description: "Github token, usually 'secrets.GITHUB_TOKEN'."
    required: true
  openai-api-key:
    description: "Provide your OpenAI API key."
    required: true
  openai-api-url:
    description: "Provide your OpenAI API url."
    required: true
  changes:
    description: "List of commits or changes to be analyzed. Should adhere to conventional commit standards."
    required: true
  version:
    description: "Provide the new release version."
    required: true
outputs:
  changelog:
    description: "The generated changelog body for the most recent release."
runs:
  using: "node20"
  main: "index.js"
branding:
  icon: cpu
  color: blue
